import { Warehouse, Columns2, Calendar, List, Type, X, Trash, Download, Ellipsis, ArrowUp, ArrowDown, ChevronDown, Mail, Sun, Boxes, Moon, CircleAlert, Loader2, ExternalLink, Menu, Check, Infinity, ChevronsUpDown, Plus, Star } from "lucide-react";

export const Icons = {
  updown: ChevronsUpDown,
  columns: Columns2,
  calendar: Calendar,
  list: List,
  text: Type,
  cross: X,
  trash: Trash,
  download: Download,
  horizontalDots: Ellipsis,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  plus: Plus,
  star: Star,
  sun: Sun,
  moon: Moon,
  chevronDown: ChevronDown,
  alert: CircleAlert,
  spinner: Loader2,
  warehouse: Warehouse,
  external: ExternalLink,
  menu: Menu,
  mail: Mail,
  boxes: Boxes,
  check: Check,
  infinity: Infinity,
};
