import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Boxes,
  Calendar,
  Check,
  ChevronDown,
  ChevronsUpDown,
  CircleAlert,
  Columns2,
  Download,
  Ellipsis,
  ExternalLink,
  Infinity,
  List,
  Loader2,
  Mail,
  Menu,
  Minus,
  Moon,
  Plus,
  Star,
  Sun,
  Trash,
  Type,
  Warehouse,
  X,
} from 'lucide-react'

export const Icons = {
  updown: ChevronsUpDown,
  minus: Minus,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  columns: Columns2,
  calendar: Calendar,
  list: List,
  text: Type,
  cross: X,
  trash: Trash,
  download: Download,
  horizontalDots: Ellipsis,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  plus: Plus,
  star: Star,
  sun: Sun,
  moon: Moon,
  chevronDown: ChevronDown,
  alert: CircleAlert,
  spinner: Loader2,
  warehouse: Warehouse,
  external: ExternalLink,
  menu: Menu,
  mail: Mail,
  boxes: Boxes,
  check: Check,
  infinity: Infinity,
}
